import java.util.ArrayList;
import java.util.Scanner;

class Student {
        int rollNo;
            String name;
                String course;

                    Student(int rollNo, String name, String course) {
                                this.rollNo = rollNo;
                                        this.name = name;
                                                this.course = course;
                    }

                        void display() {
                                    System.out.println("Roll No: " + rollNo);
                                            System.out.println("Name: " + name);
                                                    System.out.println("Course: " + course);
                                                            System.out.println("----------------------");
                        }
}

public class StudentManagementSystem {

        public static void main(String[] args) {

                    ArrayList<Student> students = new ArrayList<>();
                            Scanner sc = new Scanner(System.in);

                                    while (true) {
                                                    System.out.println("\n===== Student Management System =====");
                                                                System.out.println("1. Add Student");
                                                                            System.out.println("2. View Students");
                                                                                        System.out.println("3. Search Student");
                                                                                                    System.out.println("4. Exit");
                                                                                                                System.out.print("Enter your choice: ");

                                                                                                                            int choice = sc.nextInt();

                                                                                                                                        switch (choice) {

                                                                                                                                                            case 1:
                                                                                                                                                                                    System.out.print("Enter Roll Number: ");
                                                                                                                                                                                                        int roll = sc.nextInt();
                                                                                                                                                                                                                            sc.nextLine();

                                                                                                                                                                                                                                                System.out.print("Enter Name: ");
                                                                                                                                                                                                                                                                    String name = sc.nextLine();

                                                                                                                                                                                                                                                                                        System.out.print("Enter Course: ");
                                                                                                                                                                                                                                                                                                            String course = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                students.add(new Student(roll, name, course));
                                                                                                                                                                                                                                                                                                                                                    System.out.println("Student Added Successfully!");
                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                        case 2:
                                                                                                                                                                                                                                                                                                                                                                                                                if (students.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("No Students Found!");
                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            for (Student s : students) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            s.display();
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print("Enter Roll Number to Search: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int searchRoll = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    boolean found = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (Student s : students) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (s.rollNo == searchRoll) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    s.display();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                found = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!found) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Student Not Found!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Thank You!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.exit(0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Invalid Choice!");
                                                                                                                                        }
                                    }
        }
} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                        }
                                    }
        }
}
                        }
                    }
}